services:
  mongo:
    image: mongo:6.0
    container_name: quizi-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - quizi-network

  backend:
    build:
      context: ./backend
    container_name: quizi-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/quizi
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - quizi-network

  frontend:
    build:
      context: ./frontend
    container_name: quizi-frontend
    restart: always
    ports:
      - "4173:4173"
    environment:
      - VITE_API_BASE=http://backend:4000
    depends_on:
      - backend
    networks:
      - quizi-network

networks:
  quizi-network:

volumes:
  mongo-data:
